[workspace]
members = [
    "apps/node",
    "crates/api",
    "crates/processor",
    "crates/storage",
    "crates/types",
]
resolver = "2"

[net]
git-fetch-with-cli = true

[workspace.dependencies]
chrono = { version = "0.4.41", default-features = false }
aes-gcm = { version = "0.10", default-features = false }
rand = { version = "0.9.1", default-features = false }
base64 = { version = "0.22.1", default-features = false }
serde = { version = "1.0.219", default-features = false }
serde_json = { version = "1.0.140", default-features = false }
serde_bytes = { version = "0.11.17", features = ["std"] }
tracing = { version = "0.1.41", default-features = false }
tokio = { version = "1.45.1", default-features = false }
tokio-util = { version = "0.7.15", default-features = false }
eyre = { version = "0.6.12" }
tower = { version = "0.5.2", default-features = false }
tower-http = { version = "0.6.6", default-features = false }
async-trait = { version = "0.1.74", default-features = false }
futures-util = { version = "0.3.31", default-features = false }
hex = { version = "0.4.3", default-features = false }
hyper = { version = "1.6.0", default-features = false }
lazy_static = { version = "1.5.0", default-features = false }
thiserror = { version = "2.0.12", default-features = false }
ark-ec = { version = "0.5.0", default-features = false }
ark-ff = { version = "0.5.0", default-features = false }
ark-std = { version = "0.5.0", default-features = false }
ark-serialize = { version = "0.5.0", default-features = false }
ark-bn254 = { version = "0.5.0", default-features = false }
criterion = { version = "0.6.0", default-features = false }
utoipa = { version = "5.3.1", features = ["axum_extras", "uuid", "chrono"] }
utoipa-swagger-ui = { version = "9.0.1", features = ["axum", "reqwest"] }
utoipa-axum = "0.2"
axum = { version = "0.8.1", features = ["macros"] }
validator = { version = "0.20.0", features = ["derive"] }
mongodb = { version = "3.2.3" }
bson = { version = "2.15.0", features = ["chrono-0_4"] }
serde_repr = { version = "0.1.20", default-features = false }
tracing-subscriber = { version = "0.3.19" }
uuid = { version = "1.17.0", features = ["v7"] }
jsonwebtoken = "9.3.1"
zk = { git = "ssh://git@github.com/zk-messenger/project-m.git" }
tokio-stream = { version = "0.1.10" }
art = {  git = "ssh://git@github.com/zk-messenger/project-m.git" }
postcard = { version = "1.1.2"  }
