[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }
mongodb = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
log = "0.4.27"
futures-util = { workspace = true }
ark-ec = { workspace = true }
art = { workspace = true }
zk = { workspace = true }
ark-std = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
uuid = { workspace = true }
