[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }
mongodb = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
futures-util = { workspace = true }
art = { workspace = true }
cortado = { workspace = true }
uuid = { workspace = true, features = ["serde", "v7"] }
bson = { workspace = true, features = ["uuid-1"] }
