[package]
name = "zk-messenger-node"
version = "0.1.8"
edition = "2024"

[features]
default = ["verification"]
art_modifications = ["api/art_modifications"]
verification = ["api/verification"]

[dependencies]
api = { path = "../../crates/api" }
proof-verifier = { path = "../../crates/proof-verifier" }
types = { path = "../../crates/types" }
storage = { path = "../../crates/storage" }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "fmt",
    "env-filter",
    "json",
] }
eyre = { workspace = true }
clap = { version = "4.5.40", features = ["derive"] }
config = { version = "0.15.11", features = ["toml"] }
serde = { workspace = true, features = ["derive"] }
chrono = { workspace = true }
mongodb = { workspace = true }
