[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
storage = { path = "../storage" }
types = { path = "../types" }
axum = { workspace = true, features = ["macros"] }
validator = { workspace = true, features = ["derive"] }
utoipa = { workspace = true, features = ["axum_extras", "uuid", "chrono"] }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
utoipa-axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["full"] }
eyre = { workspace = true }
tower-http = { version = "0.6.2", features = ["fs", "trace", "cors"] }
jsonwebtoken = { workspace = true }
mongodb = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
zk = { workspace = true }
art = { workspace = true }
ark-ec = { workspace = true }
ark-serialize = { workspace = true }
ark-std = { workspace = true }
rand = { workspace = true, features = ["thread_rng"]}
log = "0.4.27"
postcard = {workspace = true}
base64 = "0.22.1"
tokio-stream = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
