[package]
name = "types"
version = "0.1.0"
edition = "2024"
autobenches = false
autobins = false
autoexamples = false
autotests = false
build = "build.rs"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
mongodb = { workspace = true }
hex = { workspace = true }
callbacks = { path = "../callback" }
zrt-art = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
eyre = { workspace = true }
ark-serialize = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
utoipa = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
bson = { workspace = true, features = ["uuid-1"] }
cortado = { workspace = true }
axum = { workspace = true }
validator = { workspace = true }
base64 = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
thiserror = { workspace = true }
serde_urlencoded = { workspace = true }
serde_with = { workspace = true, features = ["base64"] }
sha3 = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
base64urlsafedata = { version = "0.5.2 "}
postcard = { workspace = true }
zrt-zk = { workspace = true }
ark-std = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
prost-build = "0.14.1"
