[package]
name = "proof-verifier"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
tokio-util = { workspace = true }
types = { path = "../types" }
tracing = { workspace = true }
eyre = { workspace = true }
ark-ed25519 = { workspace = true }
ark-serialize = { workspace = true }
bulletproofs = { workspace = true }
cortado = { workspace = true }
zrt-zk = { workspace = true }
zkp = { workspace = true }
zrt-crypto = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
zrt-art = { workspace = true }
